import Befunge from '@/components/Befunge'
import { gridInit } from '@/grid'

export default function App() {
  return (
    <div>
      <head>
        <title>Befunge Editor</title>
        <meta name="description" content="Generated by vite" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <Befunge
        initialState={{
          ...gridInit(['&>:1-:v v *_$.@', ' ^    _$>\\:^']),
        }}
      />
    </div>
  )
}
