name: Deploy
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
     
      - name: Install
        run: |
          yarn

      - name: ESLint
        run: |
          yarn lint

  test:
    name: Run Jest Testsuite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        run: |
          yarn

      - name: ESLint
        run: |
          yarn test

  typecheck:
    name: Type Check with Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        run: |
          yarn

      - name: Typescript
        run: |
          yarn typecheck

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: 
      - test
      - typecheck
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        run: |
          yarn

      - name: Build
        run: |
          yarn tailwind
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
